name: CI/CD for Spring Boot on EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build Spring Boot app
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t my-spring-app .

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws  # Create the .aws directory
          echo "[default]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 376129861287.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker image
        run: docker tag my-spring-app:latest 376129861287.dkr.ecr.us-east-1.amazonaws.com/my-spring-app:latest

      - name: Push Docker image to ECR
        run: docker push 376129861287.dkr.ecr.us-east-1.amazonaws.com/my-spring-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Output EC2 public IP
        run: echo "EC2 instance is running at $(terraform output ec2_public_ip)"
